### PR TITLE
Feature/file download

### PR DESCRIPTION
**Pull request by rexposadas**
# What does this PR do? 

This PR adds the following endpoint: 

```
GET /results
```

This endpoint lets you download a CSV file containing results from a MongoDB query. 

Currently, it return a single row in the `electrons` collection.

# How to test this PR:

if you are connected to the DB and have data in the electrons collection, you can call the endpoint:

`curl -OJ -v http://localhost:3000/results`

You should get a file downloaded with the content being one of the rows in the electrons collections.

If not, start the app as usual:

$ make docker_build
$ export DATABASE_URL=mongodb://localhost:27017 && npm start

### CODE REVIEW

**Comment by katerynamelnykova** [comment]
I performed the following steps:
```
$ make docker_build
$ export DATABASE_URL=mongodb://localhost:27017 && npm start

$ curl -OJ -v http://localhost:3000/results
```
And received a file that contained an error message `Error: Results not found.`
Is this the expected behavior?

**Comment by rexposadas** [comment]
https://github.com/HiWARPs/cactus-backend/pull/30#issuecomment-1572016706

@katerynamelnykova I should use better error handling, probably. 

Did you have any rows in the electrons db collection?

**Comment by katerynamelnykova** [comment]
@rexposadas The electrons collection was empty. I tried to import the data using the [instructions from the README](https://oregonstate-innovationlab.atlassian.net/wiki/spaces/VOVA/pages/61145089/Docker+and+MongoDB) and got a file that contained another error message `Error: The input to objects-to-csv must be an array of objects`.

**Comment by rexposadas** [comment]
OK, I will fix the error message in the next PR

@katerynamelnykova  can you import `test_data/sample.csv` ? I had to changed the column headers of the CSV to make it more standard.

**Comment by katerynamelnykova** [comment]
@rexposadas Yes, I imported it and got the same error. If you are going to fix this error in the next PR, can I approve this PR now?

**Comment by rexposadas** [comment]
@katerynamelnykova  Thanks for checking. No need for a different PR.  I'll improve this PR and maybe add better testing.

**Pull request closed without merging**
