### PR TITLE
Dennis/cactus 28 run node inside docker container

### PR DESCRIPTION
**Pull request by DennisT98**
With the addition of the `docker-compose.yml` file, it is now possible to start multiple containers at the same time. The backend container uses an image, created from the `Dockerfile`, thus the corresponding image is based on node. This ensures that node works inside of our container, thus `server.js` works.

### CODE REVIEW

**Comment by DennisT98** [comment]
@rexposadas Do mean as a comment in the PR or in the `README.md`?

**Comment by rexposadas** [comment]
Let's also standardize on our folder nomenclature. 

The `mock_response` folder is in snake case, while `cactusMongoDB` is in camel-case. Let's keep it consistent. Can you change cactusMongoDB to snake case?

**Comment by DennisT98** [comment]
Yes I can do that.

**Comment by DennisT98** [comment]
## Description:
1. Use the terminal command `docker-compose up` in the base directory of the repository to build the images and to start the containers. This should start the server.
2. To test the connection to the server, open http://localhost:3001/ in your web browser.
3. Open a second terminal window and use the command `docker ps` to see a list of all running containers. This allows you to see the container id.
4. To enter a container use the command `docker exec -it <container id> bash`
5. To write mongo queries, open the mongo shell within the mongo container with the command `mongosh`.

**Review by rexposadas — APPROVED** [review]

**Pull request merged**
